#!/bin/bash

# Initial update and tools.
sudo apt-get remove pygame
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install screen git emacs xboxdrv mercurial

# Build bluepy.
cd ~/hindenburgFights/bluepy/bluepy
make

# Set up pygame.
cd ~
hg clone https://bitbucket.org/pygame/pygame
cd ~/pygame
sudo apt-get install python-dev python-numpy libsdl-image1.2-dev libsdl-mixer1.2-dev libsdl-ttf2.0-dev libsmpeg-dev libsdl1.2-dev  libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev
python config.py && python setup.py build && sudo python setup.py install


